### PR TITLE
Adds support for Crystal 0.36 and up. Moves to JSON::Serializable.

### LINKED ISSUE #8: JSON.mapping is now deprecated
https://github.com/manastech/crystal_slack/blob/941ab66ee68ca2e0d834e902391051c769508b21/src/slack/message.cr#L4

This spot as well as a few others are still using `JSON.mapping` instead of the `JSON::Serializable`.

### LINKED ISSUE #10: Issue in User::Profile with Crystal 0.36
https://github.com/manastech/crystal_slack/blob/941ab66ee68ca2e0d834e902391051c769508b21/src/slack/api/user.cr#L35

I'm getting this error:

```
In lib/slack/src/slack/api/user.cr:35:32

 35 | def initialize(@real_name, @email = nil)
                                 ^
Error: instance variable @email of Slack::API::User::Profile was inferred to be Nil, but Nil alone provides no information

```

### PR DESCRIPTION
**Pull request by jwoertink**
Fixes #8 
Fixes #10 

I ran the specs locally against 0.36.1 and 1.0.0. I tried to run against 0.35.1, but webmock throws some errors, so I set the version to a minimum of 0.36.1.

I also ran the formatter tool, so a few things shifted around.

### CODE REVIEW

**Comment by jwoertink** [comment]
ping @straight-shoota. I wasn't sure if anyone was watching this repo or not.

**Review by beta-ziliani — APPROVED** [review]
LGTM

**Review by straight-shoota — APPROVED** [review]

**Comment by vitobotta** [comment]
HI, I just installed the shard and I am getting the error below. Any suggestions?

```
In lib/slack/src/slack/api/user.cr:35:32

 35 | def initialize(@real_name, @email = nil)
                                 ^
Error: instance variable @email of Slack::API::User::Profile was inferred to be Nil, but Nil alone provides no information
```

**Comment by ysbaddaden** [comment]
@vitobotta we're missing a release, you should target `branch: master` in the meantime

**Comment by vitobotta** [comment]
> @vitobotta we're missing a release, you should target `branch: master` in the meantime

Will try that, thanks!

**Pull request merged**
